name: coins
description: A new Flutter project.

publish_to: "none"
version: 4.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  intl: ^0.19.0
  get_it: ^8.0.3
  flutter_bloc: ^8.1.5
  device_preview_plus: ^2.2.0
  go_router: ^14.6.2
  universal_io: ^2.2.2

dev_dependencies:
  icons_launcher: ^3.0.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

icons_launcher:
  image_path: "assets/icons/ic_launcher.png"
  platforms:
    android:
      enable: true

flutter:
 
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/
 

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
